export const SEARCH_DATA_REQUESTED = 'SEARCH_DATA_REQUESTED';
export const FETCH_SEARCH_DATA_SUCCESS = 'FETCH_SEARCH_DATA_SUCCESS';
export const FETCH_SEARCH_DATA_ERROR = 'FETCH_SEARCH_DATA_ERROR';

export const API_CONTROL_ERROR = 'API_CONTROL_ERROR';
export const NO_CONTENT = 'NO_CONTENT';