export const PRODUCT_DETAIL_REQUESTED = 'PRODUCT_DETAIL_REQUESTED';
export const FETCH_PRODUCT_DETAIL_DATA_SUCCESS = 'FETCH_PRODUCT_DETAIL_DATA_SUCCESS';
export const FETCH_PRODUCT_DETAIL_DATA_ERROR = 'FETCH_PRODUCT_DETAIL_DATA_ERROR';
export const PRODUCT_DESCRIPTION_REQUESTED = 'PRODUCT_DESCRIPTION_REQUESTED';
export const FETCH_PRODUCT_DESCRIPTION_DATA_SUCCESS = 'FETCH_PRODUCT_DESCRIPTION_DATA_SUCCESS';
export const FETCH_PRODUCT_DESCRIPTION_DATA_ERROR = 'FETCH_PRODUCT_DESCRIPTION_DATA_ERROR';

export const API_CONTROL_ERROR = 'API_CONTROL_ERROR';
export const NO_CONTENT = 'NO_CONTENT';