export interface Product {
  accepts_mercadopago?: boolean
  address?: {
    state_id?: string
    state_name?: string
    city_id?: string
    city_name?: string
  }
  attributes?: Array<any>
  available_quantity?: number
  buying_mode?: string
  catalog_listing?: boolean
  catalog_product_id?: string
  category_id?: string
  condition?: string
  currency_id?: string
  domain_id?: string
  id?: string
  installments?: any
  listing_type_id?: string
  official_store_id?: null
  order_backend?: number
  original_price?: null
  permalink?: string
  price?: number
  prices?: any
  sale_price?: null
  seller?: any
  seller_address?: any
  shipping?: {
    free_shipping?: boolean
    logistic_type?: string
    mode?: string
    store_pick_up?: boolean
    tags?: Array<string>
  }
  site_id?: string
  sold_quantity?: number
  stop_time?: string
  tags?: Array<string>
  thumbnail?: string
  thumbnail_id?: string
  title?: string
  use_thumbnail_id?: boolean
  subtitle?: string
  seller_id?: number
  base_price?: number
  initial_quantity?: number
  sale_terms?: Array<any>
  start_time?: string
  pictures?: Array<{
    id?: string
    url?: string
    secure_url?: string
    size?: string
    max_size?: string
    quality?: string
  }>
  video_id?: string
  descriptions?: Array<any>
  non_mercado_pago_payment_methods?: Array<any>
  international_delivery_mode?: string
  seller_contact?: any
  location?: any
  coverage_areas?: Array<any>
  warnings?: Array<any>
  listing_source?: string
  variations?: Array<any>
  status?: string
  sub_status?: Array<any>
  warranty?: string
  parent_item_id?: string
  differential_pricing?: any
  deal_ids?: Array<any>
  automatic_relist?: boolean
  date_created?: string
  last_updated?: string
  health?: number
}